name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - mlflow>=2.8.0
  - pandas>=2.0.0
  - numpy>=1.2.0
  - matplotlib>=1.3.0
  - scikit-learn>=1.3.0
  - seaborn>=0.12.0
  - joblib>=1.2.0
  - pip
  - pip:
      - requests
      - tenacity
