name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - imbalanced-learn==0.11.0
      - matplotlib==3.10.3
      - numpy==1.24.2  # Versi yang lebih valid
      - pandas==2.2.3
      - protobuf==3.20.0  # Versi lebih kompatibel
      - scikit-learn==1.1.0  # Versi stabil
      - seaborn==0.13.2
      - joblib==1.4.2
      - dagshub
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - scipy==1.15.3
