name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - numpy==2.2.5
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - joblib>=1.2.0
      - dagshub
