name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - imbalanced-learn==0.13.0
      - matplotlib==3.10.3
      - numpy==2.2.5
      - pandas==2.2.3
      - protobuf==6.30.2
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - joblib==1.4.2
      - dagshub
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - scipy==1.15.3
