channels:
  - conda-forge
dependencies:
  - python=3.10.0
  - pip=21.2.3
  - numpy=1.22.5  # Perbaikan versi numpy
  - pandas=1.4.2
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - mlflow=2.22.0
  - cloudpickle=3.1.1
  - pip:
    - mlflow==2.22.0
    - cloudpickle==3.1.1
    - scikit-learn==1.6.1
    - pandas==2.2.3
    - numpy==1.22.5
name: mlflow-env
