name: msml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - imbalanced-learn==0.13.0
      - matplotlib==3.6.3  # Menyesuaikan versi Matplotlib dengan versi yang lebih stabil
      - numpy==1.24.2  # Menggunakan versi numpy yang lebih baru
      - pandas==2.2.3
      - protobuf==3.20.0  # Menurunkan versi protobuf agar lebih stabil (versi 6.x bisa menyebabkan masalah kompatibilitas)
      - scikit-learn==1.0.2  # Menggunakan versi lebih stabil untuk kompatibilitas
      - seaborn==0.11.2  # Versi stabil seaborn
      - joblib==1.1.0  # Memperbarui versi joblib untuk kompatibilitas yang lebih baik
      - dagshub==0.8.3  # Memperbarui versi dagshub
      - mlflow==2.2.0
      - cloudpickle==2.2.1  # Menurunkan versi cloudpickle untuk menghindari masalah versi terbaru
      - scipy==1.8.0  # Versi scipy lebih cocok untuk stabilitas proyek
