name: msml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - imbalanced-learn==0.13.0
      - matplotlib==3.10.3
      - numpy==1.22.3  # Ganti dengan versi numpy yang lebih kompatibel
      - pandas==2.2.3
      - protobuf==6.30.2
      - scikit-learn==1.1.2  # Sesuaikan versi scikit-learn yang valid
      - seaborn==0.13.2
      - joblib==1.4.2
      - dagshub
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - scipy==1.15.3
