global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']
