name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: 'latest'
        environment-file: MLProject/conda.yaml  # Menentukan path ke conda.yaml di dalam folder MLProject
        auto-activate-base: false  # Menonaktifkan auto-activate pada base environment

    - name: Initialize Conda
      run: |
        conda init bash  # Inisialisasi conda untuk shell bash
        source ~/.bashrc  # Mengaktifkan .bashrc untuk memastikan conda diinisialisasi dengan benar
        conda --version  # Menampilkan versi conda untuk memastikan instalasi condanya berhasil
        conda info  # Memeriksa informasi tentang condanya
        conda env list  # Memeriksa apakah environment msml-env sudah ada

    - name: Run MLflow with conda run
      run: |
        conda run -n msml-env mlflow run . -P n_neighbors=3  # Menjalankan mlflow dalam environment msml-env
