name: MLflow CI Training

on:
  push:
    branches: [main]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        auto-activate-base: false

    - name: Install MLflow CLI
      run: pip install mlflow

    - name: Run MLflow Project
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --env-manager=local -P n_neighbors=3

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: ml-model
        path: Workflow-CI/MLProject/mlruns/
