name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: 'latest'
        environment-file: conda.yaml
        auto-activate-base: false

    - name: Debug Conda and Check Environment
      run: |
        conda --version  # Menampilkan versi conda untuk memastikan instalasi conda berhasil
        conda info  # Memeriksa konfigurasi conda secara keseluruhan
        conda env list  # Memeriksa environment yang ada
        conda activate msml-env  # Mengaktifkan environment msml-env
        conda list  # Memeriksa paket yang terinstal dalam environment

    - name: Run MLflow with conda run
      run: |
        conda run -n msml-env mlflow run . -P n_neighbors=3
