name: CI - MLflow Training

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: msml-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        python-version: 3.10

    - name: Install MLflow
      shell: bash -l {0}
      run: |
        pip install mlflow

    - name: Run MLflow Project (model training)
      shell: bash -l {0}
      run: |
        cd Workflow-CI/MLProject
        mlflow run . -P n_neighbors=5

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: Workflow-CI/MLProject/trained_model.pkl

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/msml-image:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-image:latest
