name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: 'latest'
        environment-file: conda.yaml
        auto-activate-base: false

    - name: Initialize conda
      run: |
        conda init bash
        source ~/.bashrc
        conda activate msml-env

    - name: Run MLflow
      run: |
        mlflow run . -P n_neighbors=3
