name: MLflow CI & Docker Build

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      # Install dependencies and MLflow
      - name: Install Dependencies and MLflow
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install -r MLProject/requirements.txt
          pip install mlflow==2.22.0

      # Jalankan MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run MLProject -P n_neighbors=3

      # Simpan artifacts hasil MLflow
      - name: Save MLflow Artifacts
        if: always()
        run: |
          mkdir -p artifacts
          cp -r MLProject/mlruns artifacts/mlruns || echo "No mlruns directory found"

      # Upload artifacts ke GitHub
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: artifacts/mlruns

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build dan push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/knn-model:latest MLProject
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/knn-model:latest
