name: MLflow CI Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env

    - name: Install MLflow
      shell: bash -l {0}
      run: |
        pip install mlflow==2.22.0

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        mlflow run MLProject -P n_neighbors=3

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest MLProject

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-model:latest
